const KEY="tradetrack_v1";
const today=new Date();
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{
  username:"trader", share:true, trades:{}, friends:[], requests:[],
  viewDate:new Date(today.getFullYear(),today.getMonth(),1).toISOString(),
  period:"month"
};
let chart;
let selectedDate=null;

function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function money(n){return `${n<0?"-":""}$${Math.abs(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parseKey(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)}
function allTrades(){return Object.entries(state.trades).flatMap(([date,arr])=>arr.map(t=>({...t,date}))).sort((a,b)=>b.date.localeCompare(a.date))}
function stats(){const ts=allTrades(), wins=ts.filter(t=>+t.pl>0), losses=ts.filter(t=>+t.pl<0), total=ts.reduce((s,t)=>s+ +t.pl,0), gp=wins.reduce((s,t)=>s+ +t.pl,0), gl=Math.abs(losses.reduce((s,t)=>s+ +t.pl,0));return {ts,wins,losses,total,gp,gl,winRate:ts.length?wins.length/ts.length*100:0,pf:gl?gp/gl:gp?Infinity:0}}
function renderSummary(){const s=stats(); document.querySelector("#totalPL").textContent=money(s.total);document.querySelector("#totalPL").className=s.total>=0?"positive":"negative";document.querySelector("#winRate").textContent=`${s.winRate.toFixed(1)}%`;document.querySelector("#winRateSub").textContent=`${s.wins.length} wins / ${s.ts.length} trades`;document.querySelector("#totalTrades").textContent=s.ts.length;let best=null;for(const [d,arr] of Object.entries(state.trades)){const v=arr.reduce((x,t)=>x+ +t.pl,0);if(!best||v>best.v)best={d,v}}document.querySelector("#bestDay").textContent=best?money(best.v):"$0.00";document.querySelector("#bestDayDate").textContent=best?parseKey(best.d).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"No trades yet"}
function renderCalendar(){const view=parseKey(state.viewDate.slice(0,10)), period=state.period, box=document.querySelector("#calendarView");if(period==="day"){document.querySelector("#calendarLabel").textContent=view.toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"});box.innerHTML=renderDay(view);return}if(period==="all"){document.querySelector("#calendarLabel").textContent="All time";box.innerHTML=renderAllYears();return}if(period==="year"){document.querySelector("#calendarLabel").textContent=view.getFullYear();box.innerHTML=renderYear(view.getFullYear());return}if(period==="week"){const start=new Date(view);start.setDate(start.getDate()-start.getDay());document.querySelector("#calendarLabel").textContent=`${start.toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${new Date(start.getFullYear(),start.getMonth(),start.getDate()+6).toLocaleDateString(undefined,{month:"short",day:"numeric"})}`;box.innerHTML=renderWeek(start);return}document.querySelector("#calendarLabel").textContent=view.toLocaleDateString(undefined,{month:"long",year:"numeric"});box.innerHTML=renderMonth(view)}
function dayHtml(d,muted=false){const k=dateKey(d),arr=state.trades[k]||[],pl=arr.reduce((s,t)=>s+ +t.pl,0), cls=pl>0?"profit":pl<0?"loss":"";return `<button class="day ${cls} ${muted?"muted":""} ${k===dateKey(today)?"today":""}" data-date="${k}"><span class="num">${d.getDate()}</span>${arr.length?`<div class="trade-count">${arr.length} trade${arr.length>1?"s":""}</div><div class="day-pl">${money(pl)}</div>`:""}</button>`}
function renderMonth(v){let first=new Date(v.getFullYear(),v.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());let html='<div class="calendar-grid">'+["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>`<div class="weekday">${x}</div>`).join("");for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);html+=dayHtml(d,d.getMonth()!==v.getMonth())}return html+"</div>"}
function renderWeek(start){let html='<div class="calendar-grid">'+["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>`<div class="weekday">${x}</div>`).join("");for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);html+=dayHtml(d)}return html+"</div>"}
function renderDay(d){return `<div class="calendar-grid">${dayHtml(d)}</div><div class="day-detail card" style="margin-top:12px;padding:16px"><div class="section-head"><div><p class="eyebrow">TRADES</p><h3>${d.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</h3></div><button class="primary" data-add="${dateKey(d)}">+ Add trade</button></div>${(state.trades[dateKey(d)]||[]).map((t,i)=>`<div class="friend-row"><div><b>${money(+t.pl)}</b><small>${escapeHtml(t.reason)}</small></div><button class="small-btn" data-delete="${dateKey(d)}:${i}">Delete</button></div>`).join("")||'<div class="empty">No trades recorded for this day.</div>'}</div>`}
function renderYear(y){let html='<div class="months-grid" style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px">';for(let m=0;m<12;m++){const v=new Date(y,m,1), total=Object.entries(state.trades).filter(([k])=>parseKey(k).getFullYear()===y&&parseKey(k).getMonth()===m).reduce((s,[,a])=>s+a.reduce((x,t)=>x+ +t.pl,0),0);html+=`<button class="card" data-month="${m}" style="padding:14px;text-align:left;color:#dce3f3;border:1px solid #222c40"><b>${v.toLocaleDateString(undefined,{month:"long"})}</b><div style="margin-top:10px" class="${total>=0?"positive":"negative"}">${money(total)}</div></button>`}return html+"</div>"}
function renderAllYears(){const years=[...new Set(Object.keys(state.trades).map(k=>parseKey(k).getFullYear()))].sort((a,b)=>b-a);if(!years.length)return '<div class="empty">No trades yet. Add a trade from the calendar to start tracking.</div>';return `<div class="card" style="padding:18px"><div class="table-wrap"><table><thead><tr><th>Year</th><th>Trades</th><th>P/L</th></tr></thead><tbody>${years.map(y=>{const ts=allTrades().filter(t=>parseKey(t.date).getFullYear()===y);const pl=ts.reduce((s,t)=>s+ +t.pl,0);return `<tr><td>${y}</td><td>${ts.length}</td><td class="${pl>=0?"positive":"negative"}">${money(pl)}</td></tr>`}).join("")}</tbody></table></div></div>`}
function openTrade(k){selectedDate=k;document.querySelector("#modalDate").textContent=parseKey(k).toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"});document.querySelector("#plInput").value="";document.querySelector("#reasonInput").value="";document.querySelector("#tradeModal").classList.add("show");setTimeout(()=>document.querySelector("#plInput").focus(),50)}
function renderAnalytics(){const s=stats();document.querySelector("#avgTrade").textContent=s.ts.length?money(s.total/s.ts.length):"$0.00";document.querySelector("#wins").textContent=s.wins.length;document.querySelector("#losses").textContent=s.losses.length;document.querySelector("#winsPct").textContent=`${s.winRate.toFixed(1)}% of trades`;document.querySelector("#lossesPct").textContent=`${s.ts.length?(s.losses.length/s.ts.length*100).toFixed(1):0}% of trades`;document.querySelector("#profitFactor").textContent=s.pf===Infinity?"∞":s.pf.toFixed(2);document.querySelector("#tradeTable").innerHTML=s.ts.slice(0,12).map(t=>`<tr><td>${parseKey(t.date).toLocaleDateString()}</td><td>${escapeHtml(t.reason)}</td><td class="${t.pl>=0?"positive":"negative"}">${money(+t.pl)}</td></tr>`).join("")||'<tr><td colspan="3" class="empty">No trades yet.</td></tr>';drawChart()}
function series(){const keys=Object.keys(state.trades).sort(), running=0;let cum=0;return keys.map(k=>{cum+=(state.trades[k]||[]).reduce((s,t)=>s+ +t.pl,0);return {k,cum,pl:(state.trades[k]||[]).reduce((s,t)=>s+ +t.pl,0),trades:(state.trades[k]||[]).length}})}
function drawChart(){const m=document.querySelector("#chartMetric").value, rows=series(), labels=rows.map(x=>parseKey(x.k).toLocaleDateString(undefined,{month:"short",day:"numeric"})),data=m==="pl"?rows.map(x=>x.cum):m==="trades"?rows.map((_,i)=>rows.slice(0,i+1).reduce((s,x)=>s+x.trades,0)):rows.map((_,i)=>{const ts=allTrades().filter(t=>t.date<=rows[i].k);return ts.length?ts.filter(t=>+t.pl>0).length/ts.length*100:0});if(chart)chart.destroy();chart=new Chart(document.querySelector("#performanceChart"),{type:"line",data:{labels,datasets:[{label:m==="pl"?"Cumulative P/L":m==="trades"?"Total trades":"Win rate %",data,borderWidth:2,tension:.35,pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#a8b2c7"}}},scales:{x:{ticks:{color:"#68738b"},grid:{color:"rgba(255,255,255,.03)"}},y:{ticks:{color:"#68738b"},grid:{color:"rgba(255,255,255,.05)"}}}}})}
function renderFriends(){document.querySelector("#myUsername").textContent=state.username;document.querySelector("#sideUsername").textContent=state.username;document.querySelector("#sideHandle").textContent="@"+state.username;document.querySelector("#avatar").textContent=state.username[0]?.toUpperCase()||"T";document.querySelector("#friendAvatar").textContent=state.username[0]?.toUpperCase()||"T";document.querySelector("#shareToggle").checked=state.share;const list=document.querySelector("#friendsList");if(!state.friends.length&&!state.requests.length){list.innerHTML='<div class="empty">No friends yet. Add someone by username to get started.</div>';return}list.innerHTML=state.requests.map(r=>`<div class="friend-row"><div class="friend-info"><div class="avatar">${r[0].toUpperCase()}</div><div><b>${escapeHtml(r)}</b><small>Incoming request</small></div></div><div class="friend-actions"><button class="small-btn accept" data-user="${escapeHtml(r)}">Accept</button><button class="small-btn decline" data-user="${escapeHtml(r)}">Decline</button></div></div>`).join("")+state.friends.map(f=>`<div class="friend-row"><div class="friend-info"><div class="avatar">${f[0].toUpperCase()}</div><div><b>${escapeHtml(f)}</b><small>Friend • performance shared</small></div></div><span class="friend-status">Connected</span></div>`).join("")}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function setTab(tab){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.remove("active"));document.querySelector("#"+tab+"Tab").classList.add("active");document.querySelector("#pageTitle").textContent=tab[0].toUpperCase()+tab.slice(1);if(tab==="analytics")renderAnalytics();if(tab==="friends")renderFriends()}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
document.querySelectorAll(".period").forEach(b=>b.onclick=()=>{state.period=b.dataset.period;document.querySelectorAll(".period").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderCalendar()});
document.querySelector("#prevBtn").onclick=()=>{let d=parseKey(state.viewDate.slice(0,10));if(state.period==="year")d.setFullYear(d.getFullYear()-1);else if(state.period==="week")d.setDate(d.getDate()-7);else if(state.period==="day")d.setDate(d.getDate()-1);else d.setMonth(d.getMonth()-1);state.viewDate=d.toISOString();renderCalendar()};
document.querySelector("#nextBtn").onclick=()=>{let d=parseKey(state.viewDate.slice(0,10));if(state.period==="year")d.setFullYear(d.getFullYear()+1);else if(state.period==="week")d.setDate(d.getDate()+7);else if(state.period==="day")d.setDate(d.getDate()+1);else d.setMonth(d.getMonth()+1);state.viewDate=d.toISOString();renderCalendar()};
document.querySelector("#todayBtn").onclick=()=>{state.viewDate=new Date(today.getFullYear(),today.getMonth(),today.getDate()).toISOString();state.period="month";document.querySelectorAll(".period").forEach(x=>x.classList.toggle("active",x.dataset.period==="month"));renderCalendar()};
document.querySelector("#calendarView").onclick=e=>{const d=e.target.closest("[data-date]");const add=e.target.closest("[data-add]");const del=e.target.closest("[data-delete]");const mon=e.target.closest("[data-month]");if(add)openTrade(add.dataset.add);else if(d){if(state.period==="day")openTrade(d.dataset.date);else{state.viewDate=parseKey(d.dataset.date).toISOString();state.period="day";document.querySelectorAll(".period").forEach(x=>x.classList.toggle("active",x.dataset.period==="day"));renderCalendar()}}else if(del){const [k,i]=del.dataset.delete.split(":");state.trades[k].splice(+i,1);if(!state.trades[k].length)delete state.trades[k];save();renderAll()}else if(mon){state.viewDate=new Date(parseKey(state.viewDate).getFullYear(),+mon.dataset.month,1).toISOString();state.period="month";document.querySelectorAll(".period").forEach(x=>x.classList.toggle("active",x.dataset.period==="month"));renderCalendar()}};
document.querySelector("#tradeForm").onsubmit=e=>{e.preventDefault();const pl=+document.querySelector("#plInput").value,reason=document.querySelector("#reasonInput").value.trim();if(!state.trades[selectedDate])state.trades[selectedDate]=[];state.trades[selectedDate].push({pl,reason,created:Date.now()});save();document.querySelector("#tradeModal").classList.remove("show");renderAll()};
document.querySelector("#closeModal").onclick=()=>document.querySelector("#tradeModal").classList.remove("show");
document.querySelector("#profileBtn").onclick=()=>{document.querySelector("#usernameInput").value=state.username;document.querySelector("#profileModal").classList.add("show")};
document.querySelector("#closeProfile").onclick=()=>document.querySelector("#profileModal").classList.remove("show");
document.querySelector("#profileForm").onsubmit=e=>{e.preventDefault();const u=document.querySelector("#usernameInput").value.trim().replace(/\s+/g,"_");if(u){state.username=u;save();renderAll();document.querySelector("#profileModal").classList.remove("show")}};
document.querySelector("#sendFriend").onclick=()=>{const input=document.querySelector("#friendInput"),u=input.value.trim().replace(/^@/,"");const msg=document.querySelector("#friendMessage");if(!u||u===state.username){msg.textContent="Enter a different username.";return}if(state.friends.includes(u)){msg.textContent="You are already friends.";return}if(!state.requests.includes(u))state.requests.push(u);save();input.value="";msg.textContent=`Request sent to @${u} (demo/local mode).`;renderFriends()};
document.querySelector("#friendsList").onclick=e=>{const u=e.target.dataset.user;if(!u)return;if(e.target.classList.contains("accept")){state.requests=state.requests.filter(x=>x!==u);if(!state.friends.includes(u))state.friends.push(u)}else if(e.target.classList.contains("decline"))state.requests=state.requests.filter(x=>x!==u);save();renderFriends()};
document.querySelector("#shareToggle").onchange=e=>{state.share=e.target.checked;save()};
document.querySelector("#chartMetric").onchange=renderAnalytics;
document.querySelector("#resetData").onclick=()=>{if(confirm("Reset all locally stored TradeTrack data?")){localStorage.removeItem(KEY);location.reload()}};
function renderAll(){renderSummary();renderCalendar();renderAnalytics();renderFriends()}
renderAll();
